services:
  redis:
    hostname: redis
    container_name: redis
    restart: always
    image: redis:7.0.15-alpine3.20
    ports:
      - "6379:6379"
    networks:
      - rate-limiter
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
        required: true
    container_name: rl-api
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    networks:
      - rate-limiter
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}

networks:
  rate-limiter:

