networks:
  rate-limiter:

services:
  redis:
    hostname: redis
    container_name: redis
    restart: always
    image: redis:7.0.15-alpine3.20
    ports:
      - "6379:6379"
    networks:
      - rate-limiter
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
